### ISSUE TITLE
Why is this bad practice? 

### ISSUE THREAD

**Issue by kw01sg** [AI3SW/ARTSLAT#1]
Saw your comment. Can explain why is this a bad practice?

https://github.com/AI3SW/BryansSignLanguageDetector/blob/59b7b8c8d7243abcbdcb99f10a89c43b6d5fcb52/flask_app/flask_app.py#L8

**Comment by bryanongse** [comment]
I think there needs to be more checks for this particular line to ensure that the model is actually being loaded. Furthermore I think that there are better ways to call a file from JavaScript
